# THIS IS NOT HOW YOU SHOULD DO DEPLOYMENTS FOR YOUR ORGANIZATION
#
# First off, the sed stuff for modifying import maps is quite hacky and shouldn't
# be what you rely on.
#
# Secondly, each angular app should be in a separate repo and deployed separately, as
# explained in the README.md.
language: node_js
node_js:
  - "node"
script:
  - cd main && npm ci && npm run build:single-spa
  - cd cip-app && npm ci && npm run build:single-spa
  - cd review-app && npm ci && npm run build:single-spa
  - cd container && npm ci && npm run build
  - cd .. && mkdir static && cp -a main/dist cip-app/dist review-app/dist static container/dist static
  - cp container/index.html static
  - sed -i 's/http:\/\/localhost:4207\/main/\/dist\/cip-app\/main/g' static/index.html
  - sed -i 's/http:\/\/localhost:4202\/main/\/dist\/review-app\/main/g' static/index.html
  - sed -i 's/http:\/\/localhost:4203\/main/\/dist\/main\/main/g' static/index.html
  - cp static/index.html static/200.html
  - echo "The static directory uploaded to surge:"
  - find static
deploy:
  provider: surge
  project: ./static/
  domain: coexisting-angular-microfrontends.surge.sh
  skip_cleanup: true